-- MySQL Script generated by MySQL Workbench
-- 07/02/14 03:26:49
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema postit
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `postit` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `postit` ;

-- -----------------------------------------------------
-- Table `postit`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `postit`.`User` ;

CREATE TABLE IF NOT EXISTS `postit`.`User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `postit`.`PostIt`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `postit`.`PostIt` ;

CREATE TABLE IF NOT EXISTS `postit`.`PostIt` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NOT NULL,
  `color` VARCHAR(45) NOT NULL,
  `dateCreated` DATE NOT NULL,
  `text` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_PostIt_User_idx` (`userId` ASC),
  CONSTRAINT `fk_PostIt_User`
    FOREIGN KEY (`userId`)
    REFERENCES `postit`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
